language: java
env:
  - CLASSPATH=`pwd`/jshop2/antlr.jar:`pwd`/jshop2/bin.build/JSHOP2.jar:.
jdk:
  - oraclejdk9
before_script:
  - pushd jshop2; make; popd
script:
  - ./compile.sh healthcare pbhealthcare_test nogui